services:
  # here for context.
  backend:
    container_name: nms_ai_backend
    build:
      context: ./services/backend
    # ... other configurations for the backend service

  transcription:
    container_name: nms_transcription_service
    build:
      context: ./services/transcription
    ports:
      - "8001:8000" # Expose container's port 8000 to your local machine's port 8001
    volumes:
      - ./services/transcription/serviceAccountKey.json:/app/secrets/serviceAccountKey.json:ro
    environment:
      - FIREBASE_SERVICE_ACCOUNT_KEY_PATH=/app/secrets/serviceAccountKey.json
    restart: unless-stopped
    # --- For GPU Acceleration ---
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]